### ISSUE TITLE
not able to see export button 

### ISSUE THREAD

**Issue by satishsure** [dfarache/Tabbed-Container-Extension#25] opened 2017-07-14 16:02 UTC
not able to see export button even after disabling the option in Additional settings."Hide Export Button" as No.The down arrow icon for export is not coming.

**Comment by satishsure** [comment] 2017-07-14 17:09
![tabextension1](https://user-images.githubusercontent.com/29802213/28222467-a05b674c-6895-11e7-95b3-eef0df69700d.png)
![tabextension2](https://user-images.githubusercontent.com/29802213/28222468-a05ef0f6-6895-11e7-8c74-a51e8f9697cb.png)

**Comment by dfarache** [comment] 2017-07-17 06:31
The export button is not meant to show at the place where you're pointing. Have a look at the following image:

![exportbutton_sample](https://user-images.githubusercontent.com/5766203/28257343-50e62792-6aca-11e7-9ab6-df15f9d38dfc.JPG)

Does it show there?

**Comment by satishsure** [comment] 2017-07-17 14:16
Its not showing there as well.Its flashing when i change any option.but it
is not appearing.

Best Regards,
Sateesh
PHONE: 224 804 1103

**Comment by dfarache** [comment] 2017-07-18 07:49
which browser and which version of Qlik Sense are you using?

**Comment by satishsure** [comment] 2017-07-18 14:26
I am using internet explorer and Chrome..I have tested with both
browsers.My Qliksense version is QS 3.2 SR4.


[image: Inline image 1]

Best Regards,
Sateesh
PHONE: 224 804 1103

**Comment by dfarache** [comment] 2017-07-19 10:31
I have just pushed a couple of changes that fix some issues that the extension had. Could you please check whether this has solved your issues?

**Comment by satishsure** [comment] 2017-07-19 14:50
Hi David,
Thanks for the concern.But no luck yet.

When don't select the tabbed container.its showing the export icon.but when
i preview it.it does not appearing.

[image: Inline image 3]


not appearing when i preview it in browser==>[image: Inline image 4]

**Comment by satishsure** [comment] 2017-08-01 14:48
Hi David,
Good Day!

Any update on this..

**Comment by enaoki** [comment] 2017-10-10 13:11
I had this issue as well, @satishsure and @dfarache. Noticed that the icons appeared in the mobile's breakpoints. I don't know if this is the best way to solve but I changed the css file and add the z-index in the class below:
```css
.qv-object-TabbedContainer_v2 .tab_container .buttonsContainer {
  position: absolute;
  top: 3px;
  right: 20px;
  display: flex;
  flex-direction: row;
  min-width: 50px;
  justify-content: flex-end;
  z-index:99999;
}
```
QS June 2017, btw.

**Comment by enaoki** [comment] 2017-10-10 13:12
QS June 2017, btw.

**Comment by dfarache** [comment] 2017-10-10 13:13
@enaoki, so you're experiencing this issue only when the extension goes into stacked mode?

Thanks btw for the CSS! Maybe that's the fix it needs.

**Comment by enaoki** [comment] 2017-10-17 13:10
On the contrary @dfarache, the icon appears when goes int stacked mode. So the issue is when extension goes into list mode. I'm glad to help.

**Comment by dfarache** [comment] 2017-10-18 09:17
@enaoki I've just merged your suggestion to master

@satishsure  hope this fixes the issue

**Closed as completed** 2017-12-12 08:44 UTC
Labels: bug
